### ISSUE TITLE
ExecuteCommand not found

### ISSUE THREAD

**Issue by FatCatTuxedo** [Jaykul/PoshConsole#15]
![image](https://user-images.githubusercontent.com/16063649/131497212-698a1a3b-9c0e-434d-a775-216439fc899e.png)

**Comment by Jaykul** [comment]
You're right. The docs were out of date!

Right before the last release I removed the ExecuteCommand interface in favor of the modern async/await style `Invoke` and `InvokeAsync` returning a Task. See [PoshConsole.cs#L182](https://github.com/Jaykul/PoshConsole/blob/695e038a0421c6ed1f8cefea76dae1cb605b218c/PoshCode.PoshConsole/PoshConsole.cs#L182).

The demo is up to date, but I've updated the ReadMe too. You can still:

```Csharp
PoshConsole.Invoke("Get-ChildItem");
```

But the async option lets you write:

```CSharp
  var users = await PoshConsole.InvokeAsync(new Command("Get-ADUser"));
```
